name : "First Demo Actoin"

on: 
  push:
    branches:
    - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action Started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line test
        run: echo "Hello World"
      - name: Run a multiple-line test
      - run: |
          echo Add other actions to build,run: echo "
          echo "Hello World
      - name: List files
        run: ls ${{ github.workspace }}
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo "$GITHUB_CONTEXT"
      