name: 'First Demo Action'

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Action Started
        run: echo "Action Started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one-line test
        run: echo "Hello World"
      - name: Run a multiple-line test
        run: |
          echo "Hello World"
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Display GitHub context
        run: echo "${GITHUB_CONTEXT}"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
